import { EMPTY_TYPE_CONSTRAINTS, EMPTY_TYPE_CONTEXT, EMPTY_TYPE_SUBSTITUTION } from './types.js';
import { EMPTY_VALUE_CONTEXT } from './values.js';

export const GLOBAL_TYPE_CONTEXT = EMPTY_TYPE_CONTEXT;
export const GLOBAL_TYPE_CONSTRAINTS = EMPTY_TYPE_CONSTRAINTS;
export const GLOBAL_TYPE_SUBSTITUTION = EMPTY_TYPE_SUBSTITUTION;
export const GLOBAL_VALUE_CONTEXT = EMPTY_VALUE_CONTEXT;
